### PR TITLE
[Fix #80] Ability to preserve traits

### LINKED ISSUE #80: Issue with create_default and traits
I have this factory, with a trait that allows changing the association general definition like this: 

```ruby
FactoryBot.define do
  factory :idea do
    association :status, :default

    trait :bla do
      association :status, :bla
    end
  end
end 
```

When I use FactoryDefault to define a default `status` like this in a shared context:

```ruby
shared_context 'My context' do  
  let_it_be(:status) { create :status }

  before do
    set_factory_default :status, status
  end
end
```

And write my spec: 

```ruby
include_context 'My context'

it do
  create :idea #=> is created with the default :status from shared context
  create :idea, :bla #=> is ALSO created with the default :status from shared context
end
```

So in practice `trait :bla` is not used at all, `set_factory_default` is overriding that. This was, at least, surprising and unexpected. I expected the trait behaviour to preveal, since it is explicitly declaring the association.

Is this intented behaviour or is this a 🐛? 

**Ruby Version:** 2.3.7
**Framework Version:** Rspec 3.6
**TestProf Version:** 0.5.0

### PR DESCRIPTION
**Pull request by Vasfed**
Fixes #80.

This adds option to `TestProf::FactoryDefault` to revert to default behaviour when factories have traits for association.

### CODE REVIEW

File: lib/test_prof/factory_default.rb [hunk 1]
```diff
@@ -9,18 +9,21 @@ module TestProf
...
+        options = args.extract_options!
+        preserve = options.delete(:preserve_traits) || FactoryDefault.preserve_traits
+
+        obj = TestProf::FactoryBot.create(name, *args, options, &block)
+        set_factory_default(name, obj, preserve)
       end
 
-      def set_factory_default(name, obj)
-        FactoryDefault.register(name, obj)
+      def set_factory_default(name, obj, preserve_traits = nil)
```
Comment (palkan) [inline lib/test_prof/factory_default.rb]: Let's make it a keyword argument and pass it as `.register(name, obj, options)`. We'll probably have more options in the future.

File: lib/test_prof/factory_default.rb [hunk 2]
```diff
@@ -29,17 +32,26 @@ def init
...
+        # default is false to retain backward compatibility
+        @preserve_traits = false
       end
 
-      def register(name, obj)
+      def register(name, obj, preserve_traits = nil)
+        unless FactoryDefault.preserve_traits
+          @store_preserve_traits[name] ||= true if preserve_traits
+        end
         store[name] = obj
```
Comment (palkan) [inline lib/test_prof/factory_default.rb]: What about storing the options along with the object itself, i.e.:

```ruby
store[name] = { record: obj, **options}
```

File: spec/integrations/factory_default_spec.rb [hunk 3]
```diff
@@ -6,6 +6,6 @@
   specify "RSpec integration", :aggregate_failures do
     output = run_rspec('factory_default')
 
-    expect(output).to include("5 examples, 0 failures")
+    expect(output).to include(" examples, 0 failures")
```
Comment (palkan) [inline spec/integrations/factory_default_spec.rb]: ?

Comment (Vasfed) [reply spec/integrations/factory_default_spec.rb]: here we are interested more in the spec passing, thought it is redundant to update test count each time the fixture spec has a test added, restored to explicit count

File: lib/test_prof/factory_default.rb (hunk 2 above)
Comment (Vasfed) [reply lib/test_prof/factory_default.rb]: First thought was to save some hash allocations, but agree, no point in chasing those several dozens additional hashes, also if we decide to make some default-for-trait-objects they can be stored in the same hash under special keys.

**Comment by Vasfed** [comment]
@palkan please see new commit

File: lib/test_prof/factory_default.rb [hunk 4]
```diff
@@ -32,27 +32,28 @@ def init
...
-        store[name]
-      end
+      def get(name, traits = nil)
+        record = store[name]
+        return unless record
 
-      def exists?(name, traits = nil)
         if traits && !traits.empty?
-          return false if FactoryDefault.preserve_traits || @store_preserve_traits[name]
+          return nil if FactoryDefault.preserve_traits || record[:preserve_traits]
```
Comment (palkan) [inline lib/test_prof/factory_default.rb]: Unnecessary `nil`

File: lib/test_prof/factory_default.rb [hunk 5]
```diff
@@ -32,27 +32,28 @@ def init
...
         end
-        store.key?(name)
+        record[:object]
+      end
+
+      def exists?(name, traits = nil)
```
Comment (palkan) [inline lib/test_prof/factory_default.rb]: Do we use `exists?` anywhere?

Comment (Vasfed) [reply lib/test_prof/factory_default.rb]: No, we don't, can be safely removed - left it for compatibility. It was public and appeared in generated documentation, someone could have used it for some test suite debugging. (sure I doubt it too)

File: lib/test_prof/factory_default.rb (hunk 4 above)
Comment (Vasfed) [reply lib/test_prof/factory_default.rb]: Enabled rubocop to check for that

File: lib/test_prof/factory_default.rb (hunk 5 above)
Comment (palkan) [reply lib/test_prof/factory_default.rb]: Let's remove then

Comment (Vasfed) [reply lib/test_prof/factory_default.rb]: Ok, done

**Comment by palkan** [comment]
Thanks! Great job!

**Comment by palkan** [comment]
Hey @Vasfed!

Could you please send me your actual email address to `palkan@evl.ms`? We plan to send some goodies to the Cult participants)

**Comment by Vasfed** [comment]
@palkan Hey! Sent email, e064395fd8a88d6d6c887132d7e1e39035e841a12fc6c5f28cc348ffb4c62b16
